In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
data = pd.read_csv('dataset_v4.csv')

In [3]:
data.head()

ID  YEAR  DATE SEASON  SIZE  AVG_TMAX  AVG_TMIN  AVG_HUM      N    P    K  \
0  125  2008     7    WET   1.5      31.5      25.2    86.83  34.50  0.0  0.0   
1  125  2007    11    DRY   1.5      30.3      24.1    69.33  53.67  0.0  0.0   
2  309  2008     6    WET   1.5      32.7      26.0    86.83  57.50  0.0  0.0   
3  313  2008     7    WET   1.2      31.5      25.2    86.83  30.67  0.0  0.0   
4  313  2007    11    DRY   1.2      30.3      24.1    69.33  38.33  0.0  0.0   

  IRRIGATION_TYPE MUNICIPALITY PROVINCE  PRODUCTION (KG)  
0         GRAVITY     STA ROSA   LAGUNA          9322.00  
1         GRAVITY     STA ROSA   LAGUNA          8850.00  
2         GRAVITY      CABUYAO   LAGUNA          7950.00  
3         GRAVITY      CABUYAO   LAGUNA          5243.92  
4         GRAVITY      CABUYAO   LAGUNA          7067.50

In [4]:
data = data.drop(['ID'], axis = 1)

In [5]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YEAR             58 non-null     int64  
 1   DATE             58 non-null     int64  
 2   SEASON           58 non-null     object 
 3   SIZE             58 non-null     float64
 4   AVG_TMAX         58 non-null     float64
 5   AVG_TMIN         58 non-null     float64
 6   AVG_HUM          58 non-null     float64
 7   N                58 non-null     float64
 8   P                58 non-null     float64
 9   K                58 non-null     float64
 10  IRRIGATION_TYPE  58 non-null     object 
 11  MUNICIPALITY     58 non-null     object 
 12  PROVINCE         58 non-null     object 
 13  PRODUCTION (KG)  58 non-null     float64
dtypes: float64(8), int64(2), object(4)
memory usage: 6.5+ KB


In [6]:
#handling missing data
data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58 entries, 0 to 57
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YEAR             58 non-null     int64  
 1   DATE             58 non-null     int64  
 2   SEASON           58 non-null     object 
 3   SIZE             58 non-null     float64
 4   AVG_TMAX         58 non-null     float64
 5   AVG_TMIN         58 non-null     float64
 6   AVG_HUM          58 non-null     float64
 7   N                58 non-null     float64
 8   P                58 non-null     float64
 9   K                58 non-null     float64
 10  IRRIGATION_TYPE  58 non-null     object 
 11  MUNICIPALITY     58 non-null     object 
 12  PROVINCE         58 non-null     object 
 13  PRODUCTION (KG)  58 non-null     float64
dtypes: float64(8), int64(2), object(4)
memory usage: 6.8+ KB


In [7]:
data.describe()

YEAR       DATE       SIZE   AVG_TMAX   AVG_TMIN    AVG_HUM  \
count    58.000000  58.000000  58.000000  58.000000  58.000000  58.000000   
mean   2007.568966   6.879310   1.294310  31.501724  24.856897  79.286897   
std       0.499546   3.433977   0.685602   0.904858   0.967926   8.742056   
min    2007.000000   1.000000   0.250000  30.300000  23.500000  69.330000   
25%    2007.000000   6.000000   0.762500  30.600000  23.900000  69.330000   
50%    2008.000000   6.500000   1.200000  31.500000  25.200000  86.830000   
75%    2008.000000   9.500000   2.000000  32.700000  26.000000  86.830000   
max    2008.000000  12.000000   2.800000  32.700000  26.000000  86.830000   

                N          P          K  PRODUCTION (KG)  
count   58.000000  58.000000  58.000000        58.000000  
mean    46.503621   4.336207   4.198276      6762.322931  
std     27.454862  10.556194  11.550021      4149.717880  
min      0.000000   0.000000   0.000000       600.000000  
25%     27.932500   0.000000   0.000000      3732.600000  
50%     38.330000   0.000000   0.000000      5818.500000  
75%     68.250000   0.000000   0.000000      8949.862500  
max    115.000000  60.000000  72.000000     17626.210000

In [8]:
data['YEAR'].value_counts()

2008    33
2007    25
Name: YEAR, dtype: int64

In [9]:
data['SEASON'].value_counts()

WET    33
DRY    25
Name: SEASON, dtype: int64

In [10]:
data['IRRIGATION_TYPE'].value_counts()

GRAVITY    56
RAINFED     1
PUMP        1
Name: IRRIGATION_TYPE, dtype: int64

In [11]:
data['MUNICIPALITY'].value_counts()

CALAUAN     21
CALAMBA     17
CABUYAO     14
BAY          2
BINAN        2
STA ROSA     2
Name: MUNICIPALITY, dtype: int64

In [12]:
data['PROVINCE'].value_counts()

LAGUNA    58
Name: PROVINCE, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

YEAR = le.fit_transform(data.YEAR)
SEASON = le.fit_transform(data.SEASON)
IRRIGATION_TYPE = le.fit_transform(data.IRRIGATION_TYPE)
MUNICIPALITY = le.fit_transform(data.MUNICIPALITY)
PROVINCE = le.fit_transform(data.PROVINCE)
data['YEAR'] = YEAR
data['SEASON'] = SEASON
data['IRRIGATION_TYPE'] = IRRIGATION_TYPE
data['MUNICIPALITY'] = MUNICIPALITY
data['PROVINCE'] = PROVINCE




In [14]:
print(data['YEAR'].unique())
print(data['SEASON'].unique())
print(data['IRRIGATION_TYPE'].unique())
print(data['MUNICIPALITY'].unique())
print(data['PROVINCE'].unique())


[1 0]
[1 0]
[0 2 1]
[5 2 3 1 4 0]
[0]


In [15]:
data.head()

YEAR  DATE  SEASON  SIZE  AVG_TMAX  AVG_TMIN  AVG_HUM      N    P    K  \
0     1     7       1   1.5      31.5      25.2    86.83  34.50  0.0  0.0   
1     0    11       0   1.5      30.3      24.1    69.33  53.67  0.0  0.0   
2     1     6       1   1.5      32.7      26.0    86.83  57.50  0.0  0.0   
3     1     7       1   1.2      31.5      25.2    86.83  30.67  0.0  0.0   
4     0    11       0   1.2      30.3      24.1    69.33  38.33  0.0  0.0   

   IRRIGATION_TYPE  MUNICIPALITY  PROVINCE  PRODUCTION (KG)  
0                0             5         0          9322.00  
1                0             5         0          8850.00  
2                0             2         0          7950.00  
3                0             2         0          5243.92  
4                0             2         0          7067.50

In [16]:
print(data)

    YEAR  DATE  SEASON  SIZE  AVG_TMAX  AVG_TMIN  AVG_HUM       N     P     K  \
0      1     7       1  1.50      31.5      25.2    86.83   34.50   0.0   0.0   
1      0    11       0  1.50      30.3      24.1    69.33   53.67   0.0   0.0   
2      1     6       1  1.50      32.7      26.0    86.83   57.50   0.0   0.0   
3      1     7       1  1.20      31.5      25.2    86.83   30.67   0.0   0.0   
4      0    11       0  1.20      30.3      24.1    69.33   38.33   0.0   0.0   
5      0    11       0  1.20      30.3      24.1    69.33   46.00   0.0   0.0   
6      1     7       1  1.20      31.5      25.2    86.83   46.00   0.0   0.0   
7      1     7       1  1.20      31.5      25.2    86.83   35.67   3.5   3.5   
8      0     2       0  1.30      31.3      23.5    69.33   33.00   7.0   7.0   
9      1     6       1  1.30      32.7      26.0    86.83   26.50  21.0  21.0   
10     1     7       1  2.45      31.5      25.2    86.83   38.00  14.0  14.0   
11     0    12       0  2.45

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import roc_auc_score, classification_report, mean_squared_error, r2_score
forest = RandomForestRegressor(n_estimators=1000,
                              criterion='mse',
                              random_state=1,
                              n_jobs=-1)
forest.fit(X_train, y_train)
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)

print('MSE train: %.3f, test: %.3f' %(
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))

print('R^2 train: %.3f, test: %.3f' %(
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))

MSE train: 870874.028, test: 3875242.384
R^2 train: 0.939, test: 0.850


In [21]:
print(forest.score(X_test, y_test))

0.8495013765624967


In [22]:
forest.predict(X_test)

array([ 8337.13074,  7365.96707, 14539.05346,  2536.02342,  4043.54676,
        3366.09389,  4863.94378,  6365.57962,  8582.60706, 14576.23689,
        1363.91488,  5792.08483])

In [23]:
X_test

YEAR  DATE  SEASON  SIZE  AVG_TMAX  AVG_TMIN  AVG_HUM      N    P    K  \
48     1     6       1   2.0      32.7      26.0    86.83  92.00  0.0  0.0   
2      1     6       1   1.5      32.7      26.0    86.83  57.50  0.0  0.0   
35     1     7       1   2.8      31.5      25.2    86.83  72.50  0.0  0.0   
46     1     6       1   0.5      32.7      26.0    86.83  23.00  0.0  0.0   
39     0    12       0   0.8      30.6      23.9    69.33  46.00  0.0  0.0   
34     1     6       1   1.0      32.7      26.0    86.83  16.75  0.0  0.0   
38     1     6       1   0.8      32.7      26.0    86.83  34.50  0.0  0.0   
19     1     6       1   1.3      32.7      26.0    86.83  80.50  0.0  0.0   
21     1     7       1   2.0      31.5      25.2    86.83  92.00  0.0  0.0   
51     1     6       1   2.5      32.7      26.0    86.83  80.50  0.0  0.0   
44     1     7       1   0.3      31.5      25.2    86.83   0.00  0.0  0.0   
3      1     7       1   1.2      31.5      25.2    86.83  30.67  0.0  0.0   

    IRRIGATION_TYPE  MUNICIPALITY  PROVINCE  
48                0             4         0  
2                 0             2         0  
35                0             4         0  
46                0             4         0  
39                0             4         0  
34                0             4         0  
38                0             4         0  
19                0             2         0  
21                0             2         0  
51                0             2         0  
44                0             4         0  
3                 0             2         0

In [ ]:
YEAR = input('Enter Year:')
MONTH = input('Enter Month:')
SEASON = input('Enter Season:')
SIZE = input('Enter Size:')
AVG_TMAX = input('Enter Temperature Max:')
AVG_TMIN = input('Enter Temperature Min:')
AVG_HUM = input('Enter Humidity:')
N = input('Enter Nitrogen Composition:')
P = input('Enter Phosporus Composition:')
K = input('Enter Potassium Composition:')
IRRIGATION_TYPE = input('Enter Irrigation Type:')
MUNICIPALITY = input('Enter Municipality:')
PROVINCE = input('Enter Province:')

out_1 = forest.predict([[float(YEAR),
                        float(MONTH),
                        float(SEASON),
                        float(SIZE),
                        float(AVG_TMAX),
                        float(AVG_TMIN),
                        float(AVG_HUM),
                        float(N),
                        float(P),
                        float(K),
                        float(IRRIGATION_TYPE),
                        float(MUNICIPALITY),
                        float(PROVINCE)]])
print('Crop yield Production:', out_1)